pureba2register/Controllers/AgregarOfertasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pureba2register.Models;

namespace pureba2register.Controllers
{   [Authorize(Roles ="Empresa")]
    public class AgregarOfertasController : Controller
    {
        private pureba2registerContext db = new pureba2registerContext();

        // GET: AgregarOfertas
        public ActionResult Index()
        {
            return View(db.AgregarOfertas.ToList());
        }

        // GET: AgregarOfertas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgregarOferta agregarOferta = db.AgregarOfertas.Find(id);
            if (agregarOferta == null)
            {
                return HttpNotFound();
            }
            return View(agregarOferta);
        }

        // GET: AgregarOfertas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AgregarOfertas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AgregarOfertaID,FechaInicio,FechaFinal,Asunto,PerfilRequerido,Descripcion")] AgregarOferta agregarOferta)
        {
            if (ModelState.IsValid)
            {
                db.AgregarOfertas.Add(agregarOferta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(agregarOferta);
        }

        // GET: AgregarOfertas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgregarOferta agregarOferta = db.AgregarOfertas.Find(id);
            if (agregarOferta == null)
            {
                return HttpNotFound();
            }
            return View(agregarOferta);
        }

        // POST: AgregarOfertas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AgregarOfertaID,FechaInicio,FechaFinal,Asunto,PerfilRequerido,Descripcion")] AgregarOferta agregarOferta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agregarOferta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agregarOferta);
        }

        // GET: AgregarOfertas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgregarOferta agregarOferta = db.AgregarOfertas.Find(id);
            if (agregarOferta == null)
            {
                return HttpNotFound();
            }
            return View(agregarOferta);
        }

        // POST: AgregarOfertas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgregarOferta agregarOferta = db.AgregarOfertas.Find(id);
            db.AgregarOfertas.Remove(agregarOferta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pureba2register/Controllers/ConsultarOfertasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pureba2register.Models;

namespace pureba2register.Controllers
{
    [Authorize(Roles = "Empresa")]
    public class ConsultarOfertasController : Controller
    {
        private pureba2registerContext db = new pureba2registerContext();

        // GET: ConsultarOfertas
        public ActionResult Index()
        {
            return View(db.AgregarOfertas.ToList());
        }

        // GET: ConsultarOfertas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConsultarOferta consultarOferta = db.ConsultarOfertas.Find(id);
            if (consultarOferta == null)
            {
                return HttpNotFound();
            }
            return View(consultarOferta);
        }

        // GET: ConsultarOfertas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ConsultarOfertas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AgregarOfertaID,FechaInicio,FechaFinal,Asunto,PerfilRequerido,Descripcion")] ConsultarOferta consultarOferta)
        {
            if (ModelState.IsValid)
            {
                db.ConsultarOfertas.Add(consultarOferta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(consultarOferta);
        }

        // GET: ConsultarOfertas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgregarOferta agregarOferta = db.AgregarOfertas.Find(id);
            if (agregarOferta == null)
            {
                return HttpNotFound();
            }
            return View(agregarOferta);
        }

        // POST: ConsultarOfertas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AgregarOfertaID,FechaInicio,FechaFinal,Asunto,PerfilRequerido,Descripcion")] AgregarOferta agregarOferta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agregarOferta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agregarOferta);
        }

        // GET: ConsultarOfertas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgregarOferta agregarOferta = db.AgregarOfertas.Find(id);
            if (agregarOferta == null)
            {
                return HttpNotFound();
            }
            return View(agregarOferta);
        }

        // POST: ConsultarOfertas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgregarOferta agregarOferta = db.AgregarOfertas.Find(id);
            db.AgregarOfertas.Remove(agregarOferta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pureba2register/Controllers/CrearPerfilEmpresasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pureba2register.Models;

namespace pureba2register.Controllers
{
    [Authorize(Roles = "Empresa")]
    public class CrearPerfilEmpresasController : Controller
    {
        private pureba2registerContext db = new pureba2registerContext();

        // GET: CrearPerfilEmpresas
        public ActionResult Index()
        {
            return View(db.CrearPerfilEmpresas.ToList());
        }

        // GET: CrearPerfilEmpresas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrearPerfilEmpresa crearPerfilEmpresa = db.CrearPerfilEmpresas.Find(id);
            if (crearPerfilEmpresa == null)
            {
                return HttpNotFound();
            }
            return View(crearPerfilEmpresa);
        }

        // GET: CrearPerfilEmpresas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CrearPerfilEmpresas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CrearPerfilEmpresaID,NombreEmpresa,Nit,DireccionEmpresa,NumeroEgresado,DescripccionEmpresa")] CrearPerfilEmpresa crearPerfilEmpresa)
        {
            if (ModelState.IsValid)
            {
                db.CrearPerfilEmpresas.Add(crearPerfilEmpresa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(crearPerfilEmpresa);
        }

        // GET: CrearPerfilEmpresas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrearPerfilEmpresa crearPerfilEmpresa = db.CrearPerfilEmpresas.Find(id);
            if (crearPerfilEmpresa == null)
            {
                return HttpNotFound();
            }
            return View(crearPerfilEmpresa);
        }

        // POST: CrearPerfilEmpresas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CrearPerfilEmpresaID,NombreEmpresa,Nit,DireccionEmpresa,NumeroEgresado,DescripccionEmpresa")] CrearPerfilEmpresa crearPerfilEmpresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(crearPerfilEmpresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(crearPerfilEmpresa);
        }

        // GET: CrearPerfilEmpresas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrearPerfilEmpresa crearPerfilEmpresa = db.CrearPerfilEmpresas.Find(id);
            if (crearPerfilEmpresa == null)
            {
                return HttpNotFound();
            }
            return View(crearPerfilEmpresa);
        }

        // POST: CrearPerfilEmpresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CrearPerfilEmpresa crearPerfilEmpresa = db.CrearPerfilEmpresas.Find(id);
            db.CrearPerfilEmpresas.Remove(crearPerfilEmpresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pureba2register/Controllers/PerfilEmpresasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pureba2register.Models;

namespace pureba2register.Controllers
{
    [Authorize(Roles = "Empresa")]
    public class PerfilEmpresasController : Controller
    {
        private pureba2registerContext db = new pureba2registerContext();

        // GET: PerfilEmpresas
        public ActionResult Index()
        {
            return View(db.CrearPerfilEmpresas.ToList());
        }

        // GET: PerfilEmpresas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrearPerfilEmpresa crearPerfilEmpresa = db.CrearPerfilEmpresas.Find(id);
            if (crearPerfilEmpresa == null)
            {
                return HttpNotFound();
            }
            return View(crearPerfilEmpresa);
        }


        // GET: PerfilEmpresas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PerfilEmpresas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CrearPerfilEmpresaID,NombreEmpresa,Nit,DireccionEmpresa,NumeroEgresado,DescripccionEmpresa")] CrearPerfilEmpresa crearPerfilEmpresa)
        {
            if (ModelState.IsValid)
            {
                db.CrearPerfilEmpresas.Add(crearPerfilEmpresa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(crearPerfilEmpresa);
        }

        // GET: PerfilEmpresas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrearPerfilEmpresa crearPerfilEmpresa = db.CrearPerfilEmpresas.Find(id);
            if (crearPerfilEmpresa == null)
            {
                return HttpNotFound();
            }
            return View(crearPerfilEmpresa);
        }
        // POST: CrearPerfilEmpresas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CrearPerfilEmpresaID,NombreEmpresa,Nit,DireccionEmpresa,NumeroEgresado,DescripccionEmpresa")] CrearPerfilEmpresa crearPerfilEmpresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(crearPerfilEmpresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(crearPerfilEmpresa);
        }


        // GET: PerfilEmpresas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PerfilEmpresa perfilEmpresa = db.PerfilEmpresas.Find(id);
            if (perfilEmpresa == null)
            {
                return HttpNotFound();
            }
            return View(perfilEmpresa);
        }

        // POST: PerfilEmpresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PerfilEmpresa perfilEmpresa = db.PerfilEmpresas.Find(id);
            db.PerfilEmpresas.Remove(perfilEmpresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pureba2register/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EGRESOFT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">





                    <li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Empresa"))
                            {
                            <li class="dropdown">

                            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                            <li>@Html.ActionLink("Agregar Oferta", "Index", "AgregarOfertas")</li>
                            <li>@Html.ActionLink("Consultar Ofertas", "Index", "ConsultarOfertas")</li>
                            <li>@Html.ActionLink("Crear Empresa", "Index", "CrearPerfilEmpresas")</li>
                            <li>@Html.ActionLink("Perfil Empresa", "Index", "PerfilEmpresas")</li>

                            </li>
                        }
                    }
                        </li>


                        <li>

                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                <li class="dropdown">


                                <li><a href="#">ROJO</a></li>
                                <li><a href="#">VERDER</a></li>
                                <li><a href="#">AMARILLO</a></li>

                                </li>
                            }
                        }
                            </li>

                            <li>

                                @if (User.Identity.IsAuthenticated)
                                {
                                    if (User.IsInRole("Egresado"))
                                    {
                                        <
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            Page 1
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>@Html.ActionLink("Información personal", "Index", "InformacionPersonals")</li>
                                            <li>@Html.ActionLink("Referencias personales", "Index", "ReferenciasPersonales")</li>
                                            <li>@Html.ActionLink("parentesco", "Index", "Parentescoes")</li>
                                            <li>@Html.ActionLink("Informacion laboral", "Index", "InformacionLaborals")</li>
                                            <li>@Html.ActionLink("Carrera profesional", "Index", "CarreraProfesionals")</li>
                                            <li>@Html.ActionLink("Rango salarial", "Index", "RangoSalarials")</li>
                                            <li>@Html.ActionLink("Tipo referencia", "Index", "TipoReferencias")</li>
                                            <li>@Html.ActionLink("Tipo estudio", "Index", "TipoEstudios")</li>
                                            <li>@Html.ActionLink("País", "Index", "Pais")</li>
                                            <li>@Html.ActionLink("Departamento", "Index", "Departamentoes")</li>
                                            <li>@Html.ActionLink("Municipio", "Index", "Municipios")</li>

                                        </ul>
                                    </li>

                                }
                            }
                                </li>



                            </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        </div>
    <div>
        <hr />
        <footer class="colorfondo">
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>